name: 🚀 Deploy Application

on:
  push:
    tags: "*"

jobs:
  deploy-application:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 🔨 Build Application
        run: |
          npm install
          npm run build

      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          name: release_artifacts
          path: |
            ${{ github.workspace }}/buildApp/power-meter-api-linux
            ${{ github.workspace }}/buildApp/power-meter-api-win.exe

      - name: Create draft release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: ${{ github.workspace }}/buildApp/power-meter-api-linux, ${{ github.workspace }}/buildApp/power-meter-api-win.exe
          commit: ${{ github.sha }}
          draft: true
          prerelease: ${{ steps.get-pm-version.outputs.PRERELEASE }}
          name: Meter API ${{ steps.get-pm-version.outputs.PM_VERSION }}
          token: ${{ secrets.TOKEN_GITHUB }}
          tag: ${{ steps.get-pm-version.outputs.PM_VERSION }}
          body: |
            ** API for Application Meter Current **